let en =  {
	"header__logo": "FITNE<span>SS</span>",
	"header__menu-1": "HOME", 
	"header__menu-2": "ABOUT US", 
	"header__menu-3": "PAGE", 
	"header__menu-4": "BLOG", 
	"header__menu-5": "CONTACTS", 
	"header__menu-6": "LOGIN", 
	"header__menu-7": "SING UP", 
	"header__menu-8": "CHOSE PLAN",
	"header__title": "MAKE YOUR BODY <span>BEAUTIFUL</span>", 
	"header__text": "Lorem ipsum dolor sit amet, consectetur.", 
	"header__btn": "GET IN TOUCH",
	"online__subtitle": "FREE 7 DAYS", 
	"online__title": "ONLINE BOOKING", 
	"online__block-people": "People", 
	"online__block-option-1": "1 Man", 
	"online__block-option-2": "2 People", 
	"online__block-option-3": "3 People", 
	"online__block-date": "Date", 
	"online__block-time": "Time", 
	"online__block-name": "Name",  
	"online__block-phone": "Phone",  
	"online__block-email": "Email", 
	"online__btn": "GET IN TOUCH",
	"welcome__title": "WELCOME TO <span>FITNESS</span>", 
	"welcome__subtitle": "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Praesentium quis, esse libero! Nihil ab excepturi, sint omnis, eius quae repellat.",
	"welcome__text": "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Perspiciatis laudantium magni nulla porro ut, dolorem facere labore quaerat voluptatum accusantium rem, reiciendis tenetur corporis cumque eos, earum dicta possimus quod!",
	"welcome__btn": "GET IN TOUCH",
	"fitness__title": "WELCOME TO <span>FITNESS</span>",
	"fitness__text": "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cum, at.",
	"fitness__block-title-1": "Basic Crossfit",
	"fitness__block-text-1": "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Unde voluptates, hic eius veritatis nihil soluta quaerat sed officiis eligendi nemo.",
	"fitness__block_btn": "GET IN TOUCH",
	"fitness__block-title-2": "Fitness Studio",
	"fitness__block-text-2": "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Unde voluptates, hic eius veritatis nihil soluta quaerat sed officiis eligendi nemo.",
	"fitness__block-title-3": "Yoga Classes",
	"fitness__block-text-3": "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Unde voluptates, hic eius veritatis nihil soluta quaerat sed officiis eligendi nemo.",
	"presonal__subtitle": "WE TRAINED WITH",
	"personal__title": "PERSONAL TRAINER",
	"personal__btn": "GET IN TOUCH",
	"expert__title": "EXPERT <span>TRAINERS</span>",
	"expert__text": "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Molestiae quasi deserunt laborum nemo, ipsam delectus.",
	"expert__block-title-1": "Sarra Miller",
	"expert__block-subtitle-1": "SPINNING TRAINER",
	"expert__block-text-1": "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Saepe, dolor culpa repudiandae at. Eum, ex!",
	"expert__block-title-2": "John Doe",
	"expert__block-subtitle-2": "SPINNING TRAINER",
	"expert__block-text-2": "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Saepe, dolor culpa repudiandae at. Eum, ex!",
	"expert__block-title-3": "Rob Black",
	"expert__block-subtitle-3": "SPINNING TRAINER",
	"expert__block-text-3": "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Saepe, dolor culpa repudiandae at. Eum, ex!",
	"free__block-subtitle": "TRU FOR FREE",
	"free__block-title": "FREE 5 DAYS PASS",
	"free__block-btn": "GET IN TOUCH",
	"footer__fitness-title": "FITNE<span>SS</span>",
	"footer__fitness-text": "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolore, numquam ex quis quia dicta, facilis qui harum incidunt fuga voluptatum veniam nam officiis, suscipit error sequi sint voluptatem, nisi ad.",
	"footer__social-text": "Follow Us:",
	"footer__fitness-form-email": "Your email...",
	"footer__fitness-form-btn": "SUBSCRIBE",
	"footer__blogs-title": "BLOGS",
	"footer__blogs-text": "Lorem ipsum dolor sit amet, consectetur adipisicing.",
	"footer__inst-title": "INSTAGRAM",
	"footer__inst-text": "View more photos"
}